# Generated by Django 2.0.1 on 2020-06-08 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nk_Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signNo', models.IntegerField(db_column='col1', default=0, verbose_name='序号')),
                ('userId', models.CharField(db_column='col2', max_length=200, verbose_name='ID')),
                ('userNm', models.CharField(db_column='col3', max_length=200, verbose_name='用户')),
                ('signDt', models.CharField(db_column='col4', max_length=200, verbose_name='打卡日期')),
                ('signDtm', models.CharField(db_column='col5', max_length=200, verbose_name='打卡时间')),
                ('signPlace', models.CharField(db_column='col6', max_length=200, verbose_name='位置')),
                ('rec_crt_tm', models.DateTimeField(db_column='rec_crt_tm', verbose_name='数据创建时间')),
            ],
            options={
                'db_table': 'nk_sign_log',
            },
        ),
        migrations.CreateModel(
            name='NkDaySign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=200)),
                ('userNm', models.CharField(max_length=50)),
                ('signDt', models.DateField()),
                ('signDtm', models.DateTimeField()),
            ],
        ),
    ]
