# Generated by Django 2.0.1 on 2020-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm',
            field=models.DateTimeField(db_column='rec_crt_tm', default='2020-06-09 07:18:35', verbose_name='数据创建时间'),
        ),
    ]
