# Generated by Django 2.0.1 on 2020-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='signDt',
            field=models.CharField(blank=True, db_column='col4', max_length=200, verbose_name='打卡日期'),
        ),
        migrations.AlterField(
            model_name='nk_sign',
            name='signDtm',
            field=models.CharField(blank=True, db_column='col5', max_length=200, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='nk_sign',
            name='signPlace',
            field=models.CharField(blank=True, db_column='col6', max_length=200, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='nk_sign',
            name='userId',
            field=models.CharField(blank=True, db_column='col2', max_length=200, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nk_sign',
            name='userNm',
            field=models.CharField(blank=True, db_column='col3', max_length=200, verbose_name='用户'),
        ),
    ]
