# Generated by Django 2.0.1 on 2020-06-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0002_auto_20200609_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm',
            field=models.DateTimeField(db_column='rec_crt_tm', default=(2020, 6, 9, 7, 20, 46, 1, 161, 0), verbose_name='数据创建时间'),
        ),
    ]
