# Generated by Django 2.0.1 on 2020-06-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0002_auto_20200609_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nk_Sign',
            new_name='Nksign',
        ),
    ]
