# Generated by Django 2.0.1 on 2020-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0003_auto_20200609_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm',
            field=models.DateTimeField(auto_now_add=True, db_column='rec_crt_tm', verbose_name='数据创建时间'),
        ),
    ]
