# Generated by Django 2.0.1 on 2020-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0004_auto_20200609_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
