# Generated by Django 2.0.1 on 2020-06-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0005_auto_20200609_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='nk_sign',
            name='rec_crt_tm1',
            field=models.DateTimeField(default=(2020, 6, 9, 7, 31, 4, 1, 161, 0)),
        ),
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm',
            field=models.DateTimeField(db_column='rec_crt_tm', verbose_name='数据创建时间'),
        ),
    ]
