# Generated by Django 2.0.1 on 2020-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0006_auto_20200609_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm1',
            field=models.DateTimeField(default=(2020, 6, 9, 7, 35, 14, 1, 161, 0)),
        ),
    ]
