# Generated by Django 2.0.1 on 2020-06-09 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0007_auto_20200609_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm1',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 7, 37, 21, 343157)),
        ),
    ]
