# Generated by Django 2.0.1 on 2020-06-09 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nksign', '0008_auto_20200609_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nk_sign',
            name='rec_crt_tm1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
